# Generated by Django 5.2.17 on 2026-09-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresas', '0002_empresa_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiaempresa',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='membresias', to='auth.group', verbose_name='roles en esta empresa'),
        ),
    ]
