# Generated by Django 5.2.17 on 2026-09-08 23:02

import apps.adjuntos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0007_activo_nivel_renovacion'),
        ('mantenimientos', '0002_mantenimiento_causa_mantenimiento_estado_final_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('factura', 'Factura de compra'), ('acta_entrega', 'Acta de entrega'), ('acta_devolucion', 'Acta de devolución'), ('foto', 'Foto del equipo'), ('informe_tecnico', 'Informe técnico'), ('cotizacion', 'Cotización de reparación'), ('garantia', 'Garantía'), ('documento_baja', 'Documento de baja'), ('evidencia_dano', 'Evidencia de daño')], max_length=20)),
                ('archivo', models.FileField(max_length=255, upload_to=apps.adjuntos.models.ruta_adjunto)),
                ('nombre_original', models.CharField(help_text='Nombre con el que se subió, para devolverlo al descargar.', max_length=255)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('generado_por_el_sistema', models.BooleanField(default=False, help_text='Actas y documentos que produce el propio sistema, no cargados por alguien.')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='activos.activo')),
                ('mantenimiento', models.ForeignKey(blank=True, help_text='Intervención concreta a la que pertenece, si aplica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='mantenimientos.mantenimiento')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activo', 'tipo'], name='adjuntos_ad_activo__ef80ca_idx')],
            },
        ),
    ]
