# Generated by Django 5.2.17 on 2026-09-10 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('empresas', '0003_membresiaempresa_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='empresas.empresa'),
        ),
    ]
