# Generated by Django 5.2.17 on 2026-09-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(help_text='Identificador corto del área, usado en las etiquetas impresas.', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('documento_identidad', models.CharField(help_text='Cédula, pasaporte o identificador interno. Único por empleado.', max_length=30, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organizacion.departamento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_a_cargo', to='organizacion.empleado'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['apellidos', 'nombres'], name='organizacio_apellid_1945ad_idx'),
        ),
    ]
