# Generated by Django 5.2.17 on 2026-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_reemplazar_documento_por_codigo_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.CharField(help_text='Edificio, local o ciudad. Ej.: «Matriz Quito».', max_length=120)),
                ('nombre', models.CharField(help_text='Lugar dentro de la sede. Ej.: «Bodega TI», «Oficina 302».', max_length=120)),
                ('detalle', models.CharField(blank=True, help_text='Precisión opcional: piso, ala, número de rack.', max_length=150)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['sede', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('sede', 'nombre'), name='ubicacion_unica_por_sede')],
            },
        ),
    ]
