# Generated by Django 5.2.17 on 2026-09-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_sede_y_tipo_de_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Es lo que se muestra al decir dónde está un equipo. Ej.: «Quito».', max_length=120),
        ),
    ]
