# Generated by Django 5.2.17 on 2026-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_sede_reemplaza_a_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('identificacion', models.CharField(blank=True, help_text='RUC o identificación tributaria de la empresa.', max_length=20)),
                ('contacto', models.CharField(blank=True, help_text='Persona que atiende la cuenta.', max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(help_text='Identificador interno del empleado (ej. TI-0001: código del área y número dentro de ella). Se genera solo si se deja vacío.', max_length=30, unique=True),
        ),
    ]
