# Generated by Django 5.2.17 on 2026-09-09 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('organizacion', '0006_proveedores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='sede',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(help_text='Identificador corto del área, usado en las etiquetas impresas.', max_length=20),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(help_text='Identificador interno del empleado (ej. TI-0001: código del área y número dentro de ella). Se genera solo si se deja vacío.', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(help_text='Cómo se la nombra internamente. Ej.: «Sede Quito Norte».', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='departamento_nombre_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='departamento_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_empleado'), name='empleado_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='proveedor_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='sede_unica_por_empresa'),
        ),
    ]
