# Generated by Django 5.2.17 on 2026-09-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_membresiaempresa_roles'),
        ('organizacion', '0007_multiempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(blank=True, help_text='RUC o identificación tributaria del partner.', max_length=20)),
                ('contacto', models.CharField(blank=True, help_text='Persona que atiende la relación.', max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True, help_text='Condiciones de la concesión: qué cubre cada parte, hasta cuándo.')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'concesionario',
                'verbose_name_plural': 'concesionarios',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nombre'), name='concesionario_unico_por_empresa')],
            },
        ),
    ]
