# Generated by Django 5.2.17 on 2026-09-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_critico', models.BooleanField(default=False, help_text='Marca las piezas cuyo reemplazo cuenta contra el umbral de la política de renovación (tarjeta madre, disco duro, fuente de poder...).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'componente del catálogo',
                'verbose_name_plural': 'catálogo de componentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=15)),
                ('fecha_intervencion', models.DateField()),
                ('tipo_responsable', models.CharField(choices=[('tecnico_interno', 'Técnico interno'), ('proveedor_externo', 'Proveedor externo')], max_length=20)),
                ('responsable', models.CharField(help_text='Nombre del técnico interno o del proveedor externo.', max_length=150)),
                ('descripcion', models.TextField(help_text='Trabajo realizado, en detalle.')),
                ('diagnostico', models.TextField(blank=True)),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='activos.activo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mantenimiento',
                'verbose_name_plural': 'mantenimientos',
                'ordering': ['-fecha_intervencion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_serie_nuevo', models.CharField(blank=True, help_text='Serie de la pieza instalada, si aplica.', max_length=120)),
                ('era_critico', models.BooleanField(default=False, editable=False)),
                ('observaciones', models.TextField(blank=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='mantenimientos.catalogocomponente')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='mantenimientos.mantenimiento')),
            ],
            options={
                'verbose_name': 'componente utilizado',
                'verbose_name_plural': 'componentes utilizados',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['activo', '-fecha_intervencion'], name='mantenimien_activo__f56d11_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['tipo'], name='mantenimien_tipo_92e93f_idx'),
        ),
    ]
