# Generated by Django 5.2.17 on 2026-09-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='causa',
            field=models.CharField(blank=True, help_text='Qué falló (pantalla, batería, disco, lentitud...). Alimenta el análisis de causas recurrentes.', max_length=150),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_final',
            field=models.CharField(choices=[('reparado', 'Reparado'), ('pendiente', 'Pendiente'), ('no_reparable', 'No reparable'), ('dado_de_baja', 'Dado de baja')], default='reparado', max_length=15),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_salida',
            field=models.DateField(blank=True, help_text='Fecha de devolución del equipo. Vacío = sigue fuera de operación.', null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='garantia_usada',
            field=models.BooleanField(default=False, help_text='Si la intervención se cubrió con la garantía del proveedor.'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='solucion',
            field=models.TextField(blank=True, help_text='Acción aplicada para resolver el problema.'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Resultado del análisis técnico.'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_intervencion',
            field=models.DateField(help_text='Fecha de ingreso a reparación.'),
        ),
    ]
