# Generated by Django 5.2.17 on 2026-09-09 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_mantenimiento_causa_mantenimiento_estado_final_and_more'),
        ('organizacion', '0006_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteutilizado',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repuestos_vendidos', to='organizacion.proveedor'),
        ),
    ]
