# Generated by Django 5.2.17 on 2026-09-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('mantenimientos', '0003_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocomponente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='catalogocomponente',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='catalogocomponente',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='catalogocomponente',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='componente_nombre_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='catalogocomponente',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='componente_codigo_unico_por_empresa'),
        ),
    ]
