# Generated by Django 5.2.17 on 2026-09-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(help_text='Prefijo del código de barras de los activos de este tipo (ej. LAP).', max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de dispositivo',
                'verbose_name_plural': 'tipos de dispositivo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_barras', models.CharField(db_index=True, editable=False, help_text='Generado por el sistema. Es el valor codificado en Code 128.', max_length=40, unique=True)),
                ('nombre', models.CharField(help_text='Nombre corto para listados y etiquetas.', max_length=150)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('numero_serie', models.CharField(max_length=120, unique=True)),
                ('especificaciones', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('en_uso', 'En uso'), ('en_bodega', 'En bodega'), ('en_mantenimiento', 'En mantenimiento'), ('dado_de_baja', 'Dado de baja')], default='en_bodega', max_length=20)),
                ('fecha_adquisicion', models.DateField(help_text='Base del cálculo de longevidad de la política de renovación.')),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True)),
                ('total_mantenimientos', models.PositiveIntegerField(default=0, editable=False)),
                ('total_componentes_criticos', models.PositiveIntegerField(default=0, editable=False)),
                ('requiere_renovacion', models.BooleanField(db_index=True, default=False, editable=False)),
                ('motivos_renovacion', models.JSONField(blank=True, default=list, editable=False)),
                ('renovacion_evaluada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('custodio', models.ForeignKey(blank=True, help_text='Vacío mientras el equipo está en bodega, sin responsable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_asignados', to='organizacion.empleado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='organizacion.departamento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.tipodispositivo')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('alta', 'Alta en inventario'), ('asignacion', 'Asignación de custodio'), ('devolucion', 'Devolución a bodega'), ('traslado', 'Traslado de área'), ('cambio_estado', 'Cambio de estado'), ('baja', 'Baja del inventario')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='activos.activo')),
                ('custodio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_custodio_anterior', to='organizacion.empleado')),
                ('custodio_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_custodio_nuevo', to='organizacion.empleado')),
                ('departamento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_departamento_anterior', to='organizacion.departamento')),
                ('departamento_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_departamento_nuevo', to='organizacion.departamento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de activo',
                'verbose_name_plural': 'movimientos de activos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activo', '-created_at'], name='activos_mov_activo__118c17_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['marca', 'modelo'], name='activos_act_marca_f67c16_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['estado'], name='activos_act_estado_c78b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['requiere_renovacion'], name='activos_act_requier_a8728c_idx'),
        ),
    ]
