# Generated by Django 5.2.17 on 2026-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaPlantillaActivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(help_text="Campo del activo, o 'espec:<Nombre>' para una característica que se guarda en las especificaciones.", max_length=80, unique=True)),
                ('etiqueta', models.CharField(help_text='Encabezado que aparece en la plantilla.', max_length=120)),
                ('ayuda', models.CharField(blank=True, help_text='Se muestra como comentario de la celda del encabezado.', max_length=255)),
                ('obligatoria', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True, help_text='Si se desactiva, la columna no se pide ni se lee.')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'columna de la plantilla de activos',
                'verbose_name_plural': 'columnas de la plantilla de activos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
