# Generated by Django 5.2.17 on 2026-09-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_renombrar_columna_custodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_fin_garantia',
            field=models.DateField(blank=True, db_index=True, help_text='Fin de la cobertura del proveedor. Vacío = el equipo no tiene garantía registrada.', null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
