# Generated by Django 5.2.17 on 2026-09-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_columnas_garantia_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='nivel_renovacion',
            field=models.CharField(db_index=True, default='ninguno', editable=False, max_length=15),
        ),
    ]
