# Generated by Django 5.2.17 on 2026-09-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_ficha_completa_del_activo'),
        ('organizacion', '0003_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoactivo',
            name='ubicacion_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_origen', to='organizacion.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='ubicacion_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_destino', to='organizacion.ubicacion'),
        ),
    ]
