# Generated by Django 5.2.17 on 2026-09-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_proveedor_es_un_catalogo'),
        ('empresas', '0001_initial'),
        ('organizacion', '0006_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='columnaplantillaactivos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='codigo_barras',
            field=models.CharField(db_index=True, editable=False, help_text='Generado por el sistema. Es el valor codificado en Code 128.', max_length=40),
        ),
        migrations.AlterField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='columnaplantillaactivos',
            name='clave',
            field=models.CharField(help_text="Campo del activo, o 'espec:<Nombre>' para una característica que se guarda en las especificaciones.", max_length=80),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='codigo',
            field=models.CharField(help_text='Prefijo del código de barras de los activos de este tipo (ej. LAP).', max_length=10),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_barras'), name='activo_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_serie'), name='activo_serie_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tipodispositivo',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='tipo_nombre_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tipodispositivo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='tipo_codigo_unico_por_empresa'),
        ),
    ]
