# Generated by Django 5.2.17 on 2026-09-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_multiempresa'),
        ('empresas', '0002_empresa_inicial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='columnaplantillaactivos',
            constraint=models.UniqueConstraint(fields=('empresa', 'clave'), name='columna_clave_unica_por_empresa'),
        ),
    ]
