# Generated by Django 5.2.17 on 2026-09-10 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_columna_unica_por_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Ej.: «RAM», «Procesador», «Resolución».', max_length=80)),
                ('unidad', models.CharField(blank=True, help_text='Ej.: «GB», «pulgadas». Se muestra junto al valor, no se guarda con él.', max_length=20)),
                ('dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('entero', 'Número entero'), ('booleano', 'Sí / No'), ('lista', 'Lista de opciones'), ('fecha', 'Fecha')], default='texto', max_length=10)),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Valores admitidos cuando el dato es una lista de opciones.')),
                ('obligatoria', models.BooleanField(default=False, help_text='Si un equipo de este tipo no puede darse de alta sin este dato.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='En qué posición aparece dentro del formulario.')),
                ('activa', models.BooleanField(default=True, help_text='Una característica que se deja de pedir se desactiva, no se borra: los equipos que ya la tienen conservan su valor.')),
                ('tipo', models.ForeignKey(help_text='El tipo de equipo que se describe con esta característica.', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='activos.tipodispositivo')),
            ],
            options={
                'verbose_name': 'característica del tipo',
                'verbose_name_plural': 'características del tipo',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'nombre'), name='caracteristica_unica_por_tipo')],
            },
        ),
    ]
