# Generated by Django 5.2.17 on 2026-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_caracteristicatipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='condicion',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], db_index=True, help_text='Si el equipo se compró nuevo o se adquirió de segunda mano. Vacío = no consta: el inventario inicial se levanta con equipos cuya procedencia ya nadie recuerda, y dar «nuevo» por supuesto sería inventarla.', max_length=10, verbose_name='condición al adquirirlo'),
        ),
    ]
