# Generated by Django 5.2.17 on 2026-09-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_activo_condicion'),
        ('organizacion', '0008_concesionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='concesionario',
            field=models.ForeignKey(blank=True, help_text='De quién es el equipo cuando está en concesión. Distinto del proveedor: ese dice a quién se le compró.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='organizacion.concesionario'),
        ),
        migrations.AddField(
            model_name='activo',
            name='propiedad',
            field=models.CharField(choices=[('propia', 'De la empresa'), ('concesion', 'En concesión')], db_index=True, default='propia', help_text='Si el equipo es de la empresa o lo pone un partner en concesión.', max_length=10),
        ),
    ]
