# Generated by Django 5.2.17 on 2026-09-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_modulepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('usuarios.ver', 'Ver usuarios'), ('usuarios.crear', 'Crear usuarios'), ('usuarios.editar', 'Editar usuarios y su asignación de roles/permisos'), ('usuarios.deshabilitar', 'Habilitar, deshabilitar, bloquear y desbloquear usuarios'), ('usuarios.restablecer_password', 'Enviar enlace de restablecimiento, forzar cambio de contraseña en el próximo inicio o cerrar sesiones activas de un usuario'), ('roles.ver', 'Ver roles y el catálogo de permisos'), ('roles.editar', 'Crear, editar y eliminar roles'), ('permisos.ver', 'Ver el catálogo de permisos y a qué módulo pertenece cada uno'), ('empresas.ver', 'Ver las empresas del sistema y en cuáles trabaja cada usuario'), ('empresas.editar', 'Crear y editar empresas'), ('empresas.asignar', 'Asignar usuarios a empresas y elegir en cuál entran por defecto'), ('configuracion.ver', 'Ver configuración del sistema'), ('configuracion.editar', 'Editar configuración del sistema'), ('activos.ver', 'Ver el inventario y la ficha de cada activo'), ('activos.crear', 'Registrar nuevos activos en el inventario'), ('activos.editar', 'Editar la ficha técnica de un activo'), ('activos.asignar', 'Asignar, trasladar y devolver activos entre custodios y áreas'), ('activos.dar_baja', 'Dar de baja activos del inventario'), ('activos.imprimir_etiqueta', 'Generar e imprimir etiquetas de código de barras'), ('activos.exportar', 'Exportar el inventario a Excel'), ('organizacion.ver', 'Ver sedes, departamentos y empleados'), ('organizacion.editar', 'Crear y editar sedes, departamentos y empleados'), ('mantenimientos.ver', 'Ver el historial de mantenimientos y sus costos'), ('mantenimientos.registrar', 'Registrar nuevas intervenciones'), ('mantenimientos.editar', 'Corregir o eliminar intervenciones registradas'), ('mantenimientos.componentes', 'Administrar el catálogo de componentes y repuestos'), ('mantenimientos.exportar', 'Exportar la bitácora de mantenimientos a Excel'), ('politicas.ver', 'Ver las políticas de renovación configuradas'), ('politicas.editar', 'Configurar los umbrales de obsolescencia'), ('adjuntos.ver', 'Ver y descargar los adjuntos de un activo'), ('adjuntos.subir', 'Adjuntar documentos y evidencias'), ('adjuntos.eliminar', 'Eliminar adjuntos'), ('alertas.ver', 'Ver el centro de alertas del parque'), ('alertas.configurar', 'Configurar los umbrales y qué alertas están activas'), ('reportes.ver', 'Ver el catálogo de reportes y su vista previa'), ('reportes.exportar', 'Descargar reportes en Excel, CSV o PDF'), ('auditoria.ver', 'Ver el registro de auditoría'), ('auditoria.ver_detalle', 'Ver el detalle (valores anteriores y nuevos) de un evento'), ('auditoria.ver_ubicacion', 'Ver la ubicación aproximada asociada a un evento'), ('auditoria.exportar', 'Exportar el registro de auditoría')]},
        ),
    ]
