# Generated by Django 5.2.17 on 2026-09-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaObsolescencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('max_mantenimientos', models.PositiveIntegerField(blank=True, help_text='Intervenciones acumuladas toleradas. Vacío = no evaluar este criterio.', null=True)),
                ('max_componentes_criticos', models.PositiveIntegerField(blank=True, help_text='Piezas críticas sustituidas toleradas. Vacío = no evaluar este criterio.', null=True)),
                ('vida_util_meses', models.PositiveIntegerField(blank=True, help_text='Longevidad máxima en meses. Vacío = no evaluar este criterio.', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('tipo_dispositivo', models.OneToOneField(blank=True, help_text='Vacío = política global, aplicable a los tipos que no tengan una propia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politica', to='activos.tipodispositivo')),
            ],
            options={
                'verbose_name': 'política de obsolescencia',
                'verbose_name_plural': 'políticas de obsolescencia',
                'ordering': ['tipo_dispositivo__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo_dispositivo__isnull', True)), fields=('tipo_dispositivo',), name='unica_politica_global')],
            },
        ),
    ]
