# Generated by Django 5.2.17 on 2026-09-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaobsolescencia',
            name='ventana_mantenimientos_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Meses hacia atrás en los que se cuentan las intervenciones. Vacío = se cuenta todo el historial del equipo.', null=True),
        ),
        migrations.AddField(
            model_name='politicaobsolescencia',
            name='vida_util_critica_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Meses a partir de los cuales el reemplazo se recomienda. Debe ser mayor que la vida útil. Vacío = no hay segundo nivel.', null=True),
        ),
        migrations.AlterField(
            model_name='politicaobsolescencia',
            name='max_mantenimientos',
            field=models.PositiveIntegerField(blank=True, help_text='Intervenciones toleradas. Vacío = no evaluar este criterio.', null=True),
        ),
        migrations.AlterField(
            model_name='politicaobsolescencia',
            name='vida_util_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Meses a partir de los cuales conviene evaluar el reemplazo. Vacío = no evaluar.', null=True),
        ),
    ]
