# Generated by Django 5.2.17 on 2026-09-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_multiempresa'),
        ('empresas', '0001_initial'),
        ('politicas', '0002_politicaobsolescencia_ventana_mantenimientos_meses_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='politicaobsolescencia',
            name='unica_politica_global',
        ),
        migrations.AddField(
            model_name='politicaobsolescencia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AddConstraint(
            model_name='politicaobsolescencia',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_dispositivo__isnull', True)), fields=('empresa', 'tipo_dispositivo'), name='unica_politica_global'),
        ),
    ]
