# Generated by Django 5.2.17 on 2026-09-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_caracteristicatipo'),
        ('empresas', '0003_membresiaempresa_roles'),
        ('politicas', '0003_multiempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('meses_vida_contable', models.PositiveIntegerField(default=36, help_text='Meses en los que el equipo termina de depreciarse. No es la vida útil de la política de renovación: un equipo depreciado puede seguir en uso.')),
                ('porcentaje_residual', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del costo que el equipo conserva al final de su vida contable. Cero significa que se deprecia por completo.', max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa')),
                ('tipo_dispositivo', models.OneToOneField(blank=True, help_text='Vacío = política global, aplicable a los tipos que no tengan una propia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politica_depreciacion', to='activos.tipodispositivo')),
            ],
            options={
                'verbose_name': 'política de depreciación',
                'verbose_name_plural': 'políticas de depreciación',
                'ordering': ['tipo_dispositivo__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo_dispositivo__isnull', True)), fields=('empresa', 'tipo_dispositivo'), name='unica_politica_depreciacion_global'), models.CheckConstraint(condition=models.Q(('meses_vida_contable__gt', 0)), name='depreciacion_vida_positiva'), models.CheckConstraint(condition=models.Q(('porcentaje_residual__gte', 0), ('porcentaje_residual__lt', 100)), name='depreciacion_residual_en_rango')],
            },
        ),
    ]
