# Generated by Django 5.2.17 on 2026-09-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dias_sin_asignar', models.PositiveIntegerField(default=90, help_text='Días en bodega sin asignarse a partir de los cuales se avisa.')),
                ('dias_reparacion_pendiente', models.PositiveIntegerField(default=15, help_text='Días en reparación sin fecha de salida a partir de los cuales se avisa.')),
                ('dias_sin_actualizacion', models.PositiveIntegerField(default=365, help_text='Días sin ningún cambio en la ficha a partir de los cuales se avisa.')),
                ('avisar_proximos_a_reemplazo', models.BooleanField(default=True)),
                ('avisar_garantias_por_vencer', models.BooleanField(default=True)),
                ('avisar_demasiadas_reparaciones', models.BooleanField(default=True)),
                ('avisar_sin_asignar', models.BooleanField(default=True)),
                ('avisar_reparaciones_pendientes', models.BooleanField(default=True)),
                ('avisar_custodios_inactivos', models.BooleanField(default=True)),
                ('avisar_sin_actualizacion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'configuración de alertas',
                'verbose_name_plural': 'configuración de alertas',
            },
        ),
    ]
