# Generated by Django 5.2.17 on 2026-09-09 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalertas',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que reciben el resumen. Solo los que pueden ver las alertas.', related_name='alertas_suscritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='dia_envio_semanal',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, help_text='Día de la semana del envío, cuando la frecuencia es semanal.'),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='frecuencia',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal')], default='diaria', help_text='Cada cuánto se envía el resumen.', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='notificaciones_activas',
            field=models.BooleanField(default=False, help_text='Enviar el resumen de alertas por correo a los destinatarios elegidos.'),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='omitir_si_no_hay_pendientes',
            field=models.BooleanField(default=True, help_text='No enviar el correo los días en que ninguna alerta tiene equipos pendientes.'),
        ),
        migrations.AddField(
            model_name='configuracionalertas',
            name='ultimo_envio',
            field=models.DateField(blank=True, help_text='Fecha del último resumen enviado. Evita que dos pasadas del cron dupliquen.', null=True),
        ),
        migrations.CreateModel(
            name='EnvioAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resultado', models.CharField(choices=[('enviado', 'Enviado'), ('omitido', 'Omitido'), ('fallido', 'Fallido')], db_index=True, max_length=10)),
                ('origen', models.CharField(choices=[('programado', 'Programado'), ('prueba', 'Prueba manual')], db_index=True, default='programado', max_length=12)),
                ('motivo', models.CharField(blank=True, help_text='Por qué se omitió o falló. Vacío cuando el envío fue correcto.', max_length=200)),
                ('destinatarios', models.JSONField(blank=True, default=list, help_text='Identificadores de los usuarios que lo recibieron.')),
                ('total_alertas', models.PositiveIntegerField(default=0)),
                ('total_elementos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'envío de alertas',
                'verbose_name_plural': 'envíos de alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='alertas_env_created_d5ca94_idx')],
            },
        ),
    ]
