# Generated by Django 5.2.17 on 2026-09-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_configuracionalertas_destinatarios_and_more'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalertas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
    ]
