# Generated by Django 5.2.17 on 2026-09-10 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_multiempresa'),
        ('empresas', '0003_membresiaempresa_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='envioalertas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='empresas.empresa'),
        ),
        migrations.AddConstraint(
            model_name='configuracionalertas',
            constraint=models.UniqueConstraint(fields=('empresa',), name='config_alertas_unica_por_empresa'),
        ),
    ]
